name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  actions: read


jobs:
###############################################################################
# Test
###############################################################################

  test:

    name: Test

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-test.yml@v1

    with:

      runner: ubuntu-latest

      python-versions: '["3.11","3.12"]'

      working-directory: services/api-gateway

      requirements-file: requirements.txt

      lint: true

      run-tests: true

      artifact-name: api-test-results

###############################################################################
# CodeQL
###############################################################################

  codeql:

    name: CodeQL

    needs: test
    permissions:
      contents: read
      actions: read
      security-events: write

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-codeql.yml@v1

    with:

      runner: ubuntu-latest

      languages: python

      build-mode: none

###############################################################################
# SonarQube
###############################################################################

  sonarqube:

    name: SonarQube

    needs: test

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-sonarqube.yml@v1

    with:

      runner: sonar
      project-base-dir: .

      download-artifact: true

      artifact-name: api-test-results-3.12

      quality-gate: true

    secrets:

      sonar-token: ${{ secrets.SONAR_TOKEN }}

      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

###############################################################################
# Docker Build
###############################################################################

  docker-build:

    name: Docker Build

    needs:

      - test
      - codeql

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-docker-build.yml@v1

    with:

      runner: ubuntu-latest

      context: services/api-gateway

      dockerfile: services/api-gateway/Dockerfile

      image-name: auth-gateway

      image-tag: ${{ github.sha }} 

      save-artifact: true

      artifact-name: docker-image

###############################################################################
# Trivy
###############################################################################

  trivy:

    name: Trivy Scan

   
    permissions:
      contents: read
      security-events: write

    needs: docker-build

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-trivy.yml@v1

    with:

      scan-type: image

      scan-target: ${{ needs.docker-build.outputs.image }}

      download-artifact: true

      artifact-name: ${{ needs.docker-build.outputs.artifact-name }}

      severity: HIGH,CRITICAL

      scanners: vuln,secret

      report-artifact-name: trivy-results

  convert-owner:

      name: Convert Repository Owner to Lowercase

      runs-on: ubuntu-latest

      outputs:
        owner: ${{ steps.owner.outputs.owner }}

      steps:

        - name: Convert owner
          id: owner
          shell: bash
          run: |
            echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
###############################################################################
# Docker Push
###############################################################################

  docker-push:

    name: Docker Push

    needs: 
      - trivy
      - docker-build
      - convert-owner
    permissions:
      contents: read
      packages: write

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-docker-push.yml@v1

    with:

      runner: ubuntu-latest

      registry: ghcr.io

      registry-username:  ${{ needs.convert-owner.outputs.owner }}

      image-name: ${{ needs.docker-build.outputs.image-name }}

      image-tag: ${{ needs.docker-build.outputs.image-tag }}

      artifact-name: ${{ needs.docker-build.outputs.artifact-name }}

    secrets:

      registry-password: ${{ secrets.GITHUB_TOKEN }}



###############################################################################
# deploy with helm
###############################################################################
  deploy-helm:

    name: Deploy helm 
    needs: 
      - docker-build
      - docker-push
    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-deploy-helm.yml@v1
    with: 
      runner: k3s-helm
      application: auth-gateway 
      namespace: myapp
      helm-chart: ./helm/auth-gateway 
      values-file: ./helm/auth-gateway/values.yaml 
      image-repository: ghcr.io/ahmadzadeh920/auth-gateway
      image-tag: ${{ github.sha }} 
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
     

###############################################################################
# deploy with Kubernetes
###############################################################################

  deploy-Kubernetes:
    name: Deploy Kubernetes 
    needs: 
      - docker-build
      - docker-push
    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-deploy-kubernetes.yml@v1
    with:
      runner: k3s-kubectl
      application: auth-gateway
      namespace: myapp
      manifest: ./k8s
      image-repository: ghcr.io/ahmadzadeh920/auth-gateway
      image-tag: ${{ github.sha }}
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
     
###############################################################################
# deploy with docker-compose 
###############################################################################

  deploy-docker-compose:
    name: Deploy docker compose 
    needs: 
      - docker-build
      - docker-push
    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-deploy-docker-compose.yml@v1
    with:
      runner: docker-compose
      environment: production
      compose-file: ./docker-compose-pro.yml
      image: ghcr.io/ahmadzadeh920/auth-gateway
      image-tag: ${{ github.sha }}
      remote-directory: /home/fatemeh/app   # add this line
    secrets:
      ssh-host: ${{ secrets.SSH_HOST }}
      ssh-user: ${{ secrets.SSH_USER }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      ghcr-username: ${{ github.actor }}
      ghcr-token: ${{ secrets.GHCR_PAT }}
     

###############################################################################
# Repository Sync
###############################################################################

  sync:

    name: Repository Sync
  

    needs: 
      - Deploy-Kubernetes 

    uses: Ahmadzadeh920/ci-toolkit/.github/workflows/reusable-sync.yml@v1


    with:

      source-branch: main

      target-branch: release

      target-repository: Ahmadzadeh920/auth-gateway-platform

    secrets:
      target-token: ${{ secrets.REPO_SYNC_TOKEN }}


